<div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Qui sommes nous</a></div>
          <div class="presentation">
          	<h2>Qui sommes nous ?</h2>
            <p>PHONEA SARL est une société à responsabilité limitée, au capital de 8 000 euros, dont le siège social est 12, Square de la Garenne, 95500 - GONESSE, immatriculée au Registre du Commerce et des Sociétés (RCS) de PANTOISE sous le n° B 513 652 743, n° SIRET est 51365274300016, et le code APE : 6190Z. </p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
          </div>		
    	  
        </div>
    </div>