<div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Boutique</a></div>
          <div class="presentation">
          	<img src="<?php echo $this->baseUrl(); ?>/images/boutique_gsm_express.png" class="img_boutique" />
            <div class="info_boutique">
            	<img src="<?php echo $this->baseUrl(); ?>/images/venir-au-magasin.png" class="img_admag" />
                <span class="info_addmag">30, rue des Sarrazins - 59000 Lille <br />( Wazemmes place du marché )</span>
                <img src="<?php echo $this->baseUrl(); ?>/images/map-min.gif" class="map_boutique" />
                <img src="<?php echo $this->baseUrl(); ?>/images/venir-en-metro.gif" class="img_admetro" />
                <span class="info_addmag">Métro 1 - Station : Gambetta</span>
            </div>
          </div>		
    	  
        </div>
    </div>