
    <div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Conditions générales de vente</a></div>
          <div class="presentation">
          	<h2>Conditions générales de vente </h2>
            <p><strong>Article 1 – Dispositions générales :</strong> <br /><br />
            Les présentes Conditions Générales s’appliquent de plein droit à toutes interventions de « GSM EXPRESS » marque de la société « PHONEA SARL », qui propose ses prestations par l’intermédiaire des son site Internet « www.gsm-express.fr ».<br /><br />
            Les services sont proposés au client, sous réserve de son acceptation des présentes Conditions Générales. Le client déclare et reconnaît, en conséquence, avoir lu les présentes Conditions Générales. Le seul fait de faire appel à GSM EXPRESS entraîne l'acceptation pure et simple de ces Conditions Générales.<br /><br />
            La demande d’intervention engage les parties suivantes : le client qui bénéficiera de la prestation et GSM EXPRESS  prestataire de l’intervention, dont l’établissement se situe au 30, rue des Sarrasins, 59000 - LILLE  et qui est le point de dépôt après réception de votre matériel.<br /><br />
            Le client peut commander une ou plusieurs interventions par différents moyens : par téléphone, par mail en complétant le formulaire sur le site « www.gsm-express.fr » et en l’envoyant à l’adresse « contact@gsm-express.fr » ou par courrier postal. L’ensemble des coordonnées de GSM EXPRESS est disponible sur ce site Internet.<br /><br />
            Ces présentes Conditions Générales, les tarifs ainsi que les prestations proposées peuvent être modifiés à tout moment. Seule la dernière version de ces informations est disponible sur le site www.gsm-express.fr.<br /><br />
            <strong>Article 2 – Conditions d’intervention :</strong><br /><br />
            GSM EXPRESS s’engage à intervenir sur les appareils de télécommunications, informatiques et consoles suite à une demande d’intervention par l’utilisateur. Sur cette dernière seront indiqués le type de matériel, la marque et le numéro de série, un premier diagnostic de panne ainsi que la solution proposée.<br /><br />

Pour les interventions à domicile (au bureau) et dans le cas où l'intervention nécessite des tests supplémentaires afin de déterminer l'origine exacte de la panne, GSM EXPRESS proposera au client d'emporter son matériel pour réparation dans son atelier (situé au 30, rue des Sarrasins, 59000 - LILLE).<br /><br />

GSM EXPRESS fournit les prestations dans le cadre d'une obligation de moyens. GSM EXPRESS s’engage à mettre toutes ses ressources en oeuvre pour l’exécution des prestations. Cependant, au regard des aléas techniques du réseau Internet ainsi que des politiques des prestations techniques, GSM EXPRESS n’est tenue, au titre de l’exécution des prestations, que d’une obligation de moyen et non de résultat.<br /><br />
			<strong>Article 3 – Type d’intervention :</strong><br /><br />
            GSM EXPRESS s’engage à intervenir suite à une demande du client pour les prestations suivantes :<br /></p>
            <ul>

            <li>Réparation de téléphone portable, PC, consoles de jeux, Ipod, tablette,...</li>
            <li>Dépannage matériel et logiciel chez le client au centre ville de Lille et ses environs, dans ses locaux, ou à distance,</li>
            <li>Installation et configuration de logiciel et de matériel</li>
            <li>Boutiques en ligne : (Affiliation) Recommandations produits et services de ses partenaires marchands par liens, bannières, boutiques en marque blanche. Les produits présentés sur le site www.gsm-express.fr et toute autre prestation de services disponibles sur ce site.</li>
            
            </ul>
            <p>
            <strong>Article 4 – Paiement de l’intervention ou produit :</strong><br /><br />
            La somme due pour la prestation est exigible le jour même du déplacement ou de l'intervention à la remise du matériel réparé. Le prix dépend du type d’intervention effectuée.<br /><br />
            La somme sera perçue au comptant soit en espèce, soit par chèque à l’ordre de PHONEA SARL, soit en ligne par paiement sécurisé Paypal ou virement bancaire.<br /><br />
            <strong>Article 5 – Tarifs :</strong><br /><br />
            Les tarifs des prestations s’entendent en Euro Toutes Taxes Comprises (€ TTC) pour les particuliers et pour les professionnels. Les tarifs sont communiqués au client lors du dépôt du matériel et de la signature du bon de commande en magasin ou par devis validé d’un commun accord entre le client et GSM EXPRESS. Les tarifs des prestations effectuées sur le lieu de résidence du client ou le local d’une entreprise donne lieu à une facturation minimale d’une heure et ce quel que soit l’objet de la prestation.<br /><br />
            <strong>Article 6 – Garantie – Responsabilité :</strong><br /><br />
            GSM EXPRESS ne peut être tenue responsable de dommages résultants de causes extérieures à l’appareil (dégâts des eaux, envoi postal, ...), d’un emploi, d’une installation ou d’un branchement non conformes aux spécifications et aux prescriptions du constructeur, d’une utilisation nuisible à la bonne conservation de l’appareil, d’une utilisation de périphériques ou d’accessoires non adaptés,...<br />
            GSM EXPRESS ne peut être tenue responsable de la destruction de fichiers et de logiciels consécutifs à des pannes ou à des dommages occasionnés par l’utilisation de logiciels acquis par des moyens illégaux. Le client reste responsable des données présentes sur ses équipements. En conséquence, le client prendra toutes les précautions d'usage afin d'assurer les sauvegardes de ses données personnelles. La responsabilité de GSM EXPRESS, en cas de pertes totales ou partielles de données de quelque sorte que ce soit, ne peut être engagée.<br /><br />
            <strong>Article 7 – Restrictions :</strong><br /><br />
            GSM EXPRESS ne pourra assurer ses prestations, si l’environnement physique des équipements est non conforme aux prescriptions du constructeur et/ou distributeur et/ou fournisseur et/ou aux règles de sécurité; si les équipements ont fait état d’une manipulation anormale (volontaire ou non) ayant modifié leurs environnements physiques; en cas d’événement accidentel, de force majeure ou d’une cause exonératoire limitant partiellement ou totalement l’accès des équipements pour lesquels le client a expressément demandé une prestation à GSM EXPRESS notamment si les équipements sont inaccessibles pour quelque raison que ce soit, que les conditions d’alimentation électrique, téléphonique ou autres sont défectueuses ou s’il est impossible d’accéder au/dans le lieu de résidence du client. Pour ces raisons et conformément à l’Article 5, GSM EXPRESS facturera une heure d’intervention pour couvrir les frais de déplacement.<br /><br />
            <strong>Article 8 - Clause de parfaite information :</strong><br /><br />
            Le client déclare expressément avoir reçu de GSM EXPRESS toutes les informations et conseils nécessaires à la jouissance de l'objet de sa commande et renonce à rechercher sa responsabilité de ce fait.<br /><br />
            <strong>Article 9 – Confidentialité :</strong><br /><br />
            GSM EXPRESS ne divulgue aucune information concernant le client et ne permet pas à des tiers de connaître directement ou indirectement le détail des interrogations effectuées par le client et d'une manière générale aucune donnée confidentielle au sens de la loi informatique et liberté. Conformément à la loi 78-17 du 6 Janvier 1978, le client dispose à tout moment d'un droit d'accès et de rectification. Pour exercer ce droit il suffit de prendre contact avec GSM EXPRESS.
             </p>
             <p>&nbsp;</p>
          </div>		
    	  
        </div>
    </div>