
    <div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Mentions légales</a></div>
          <div class="presentation">
          	<h2>Mentions légales </h2>
            <p>
            La marque GSM EXPRESS et le site Internet <a href="www.gsm-express.fr">www.gsm-express.fr</a> ainsi que tout son contenu et ses composants sont la propriété de la société PHONEA SARL.<br /><br />
            PHONEA SARL est une société à responsabilité limitée, au capital de 8 000 euros, dont le siège social est 12, Square de la Garenne, 95500 - GONESSE, immatriculée au Registre du Commerce et des Sociétés (RCS) de PANTOISE sous le n° B 513 652 743, n° SIRET est 51365274300016, et le code APE : 6190Z.<br /><br />
            Le magasin et point de dépôt situé à l’adresse 30, rue des Sarrasins, 59000 – LILLE est un site enregistré par la société PHONEA SARL. <br /><br />
            Le contenu du site <a href="www.gsm-express.fr">www.gsm-express.fr</a> respecte les lois françaises et internationales en vigueur.<br /><br />
            
Les utilisateurs du site <a href="www.gsm-express.fr">www.gsm-express.fr</a> disposent d’un droit d’accès, de modification, de rectification et de suppression des données personnelles les concernant conformément à la loi libertés et informatique du 6 janvier 1978.
            
             </p>
             <p>&nbsp;</p>
          </div>		
    	  
        </div>
    </div>