
    <div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Recycler mon téléphone</a></div>
          <div class="presentation">
			<div class="recycle">
            	<div class="dsp_recycle">
                	<div class="rechat_mobile"></div>
                    <div class="recycle_left">
                    	<h2>Donnez une nouvelle vie à votre <br />mobile</h2>
                        <p>
                        Vous avez chez vous un ou plusieurs téléphones usagés qui ne servent plus ou en panne. <a href="">GSM EXPRESS</a> vous les rachète jusqu'à 200€ quelque soit la marque et le modèle.<br /><br />
                        En vendant votre mobile vous donnerez une seconde vie à votre appareil et contribuerez à la sauvegarde de l'environnement. 
                        </p>
                    </div>
                    <img src="<?php echo $this->baseUrl(); ?>/images/sep_recycler.gif" class="sep_recycle" />
                  <div class="recycle_right">
                    	<h2>Comment ça marche ?</h2>
                        <p>
                        <img src="<?php echo $this->baseUrl(); ?>/images/flech.gif" />&nbsp;&nbsp;<font color="#FF3366">1</font> - Amenez votre téléphone en magasin.<br /><br />
                        <img src="<?php echo $this->baseUrl(); ?>/images/flech.gif" />&nbsp;&nbsp;<font color="#FF3366">2</font> - Un technicien vous reçoit et fait une estimation de votre téléphone.
                        <br /><br />
                        <img src="<?php echo $this->baseUrl(); ?>/images/flech.gif" />&nbsp;&nbsp;<font color="#FF3366">3</font> - Si vous êtes d'accord, vous repartez immédiatement avec votre argent..</p>
                    </div>
                </div>
            </div>
          </div>		
    	  
        </div>
    </div>