
    <div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Plan du site</a></div>
          <div class="presentation">
          <div class="plan_site">
          	<ul>
            	<li><a href="">Accueil</a></li>
                <li>
                	<a href="#">Réparation</a>
                	<ul>
                		<li><a href="/reparation-iphone.php">Mode d'emploi devis mobile</a></li>
                        <li><a href="/reparation-emploi.php">Mode d'emploi     </a></li>
                        <li><a href="/reparation-informatique.php">Devis informatique   </a></li>
                        
                	</ul>
                </li>
                
                <li>
                	<a href="#">Accessoires</a>
                	<ul>
                		<li><a href="/accessoires.php">Mobile</a></li>
                        <li><a href="/accessoires-informatiques.php">Informatique</a></li>
                	</ul>
                </li>
                
                
                <li><a href="/recycler.php">Recycler mon téléphone</a></li>
                
                <li><a href="/boutiques.php">Boutique</a></li>
                
                <li><a href="/contact.php">Contact</a></li>
                
                <li><a href="/qui-sommes-nous.php">Qui-Sommes-nous ?</a></li>
                
                <li><a href="/conditions-generales-de-vente.php">Conditions générales de vente</a></li>
                
                <li><a href="/contact.php">Contact</a></li>                                                                
            </ul>
            </div>
          </div>		
    	  
        </div>
    </div>