
    <div id="container">
    	<div class="content">
        	<div class="flash_index">
              <object id="FlashID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="724" height="424">
                <param name="movie" value="swf/iphone.swf" />
                <param name="quality" value="high" />
                <param name="wmode" value="transparent" />
                <param name="swfversion" value="6.0.65.0" />
                <!-- Cette balise param invite les utilisateurs de Flash Player en version 6.0 r65 et ultérieure à télécharger la version la plus récente de Flash Player. Supprimez-la si vous ne voulez pas que cette invite soit visible. -->
                <param name="expressinstall" value="Scripts/expressInstall.swf" />
                <!-- La balise <object> suivante est destinée aux navigateurs autres qu'IE. Supprimez-la d'IE à l'aide d'IECC. -->
                <!--[if !IE]>-->
                <object type="application/x-shockwave-flash" data="swf/iphone.swf" width="724" height="424">
                  <!--<![endif]-->
                  <param name="quality" value="high" />
                  <param name="wmode" value="transparent" />
                  <param name="swfversion" value="6.0.65.0" />
                  <param name="expressinstall" value="Scripts/expressInstall.swf" />
                  <!-- Le navigateur affichera le contenu alternatif suivant pour les utilisateurs d'un lecteur Flash de version 6.0 ou de versions plus anciennes. -->
                  <div>
                    <h4>Le contenu de cette page nécessite une version plus récente d’Adobe Flash Player.</h4>
                    <p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Obtenir le lecteur Adobe Flash" /></a></p>
                  </div>
                  <!--[if !IE]>-->
                </object>
                <!--<![endif]-->
              </object>
            </div>
            <div class="devis">
            	<div class="head_devis">
                	<h2>Devis immédiat</h2>
                </div>
				<form method="post" action="pdf/getdevis1.php" enctype="multipart/form-data">
                <div class="devis_form_input">
                	<label for="" class="devis_label">Nom &amp; Pr&eacute;nom : </label>
                    <input type="text" class="devis_input" name="nom" id="nom" />
                </div>
              <div class="devis_form_input">
                	<label for="" class="devis_label">Adresse : </label>
                    <textarea class="devis_textarea" rows="" cols="" name="adresse" id="adresse"></textarea>
                </div>
              <div class="devis_form_input">
               	<label for="" class="devis_label">Email  : </label>
                	<input type="text" class="devis_input" name="email" id="email" />
                </div>
              <div class="devis_form_input">
               	<label for="" class="devis_label">Téléphone  : </label>
                	<input type="text" class="devis_input" name="tel" id="tel" />
                </div>
                <div class="devis_form_input">
               	<label for="" class="devis_label">Type de matériel :</label>
                	<select class="devis_select" name="materiel">
                    	<option value="1">Iphone</option>
                    	<option value="4">Ipad / Mini ipad</option>
                    	<option value="3">Autres mobiles</option>
                    	<option value="2">Informatiques</option>
                    	<option value="5">Consoles de jeux</option>
                    </select>
              </div>
              <div class="devis_form_input">
               	<label for="" class="devis_label">Code IEMI, Adresse MAC ou Référence<br />
           	    de votre matériel  : </label>
                	<input type="text" class="devis_input" name="code" id="code" />
              </div>
              <div class="devis_form_input">
               	<label for="" class="devis_label">Mode de paiement : </label>
                	<span class="devis_radio" id="mode1"></span>                    
                    <span class="devis_radio_label">Par Chéque </span>
                	<span class="devis_radio" id="mode2"></span>
                    <span class="devis_radio_label">En boutique</span>
                    <input type="hidden" name="mode_p" id="mode_p" />
              </div>
              <div class="devis_form_input">
              	<input type="submit" class="devis_submit" name="send_reps_iphone" value="" />
              </div>
              </form>            </div>
            <div class="product_iphone">
            	<div class="iphone">
                	<div class="head_product">
                   	  <h2><i>Iphone</i></h2>
                    </div>
                  <img src="images/iphone.jpg" />
                    <p><strong>GSM EXPRESS </strong>est spécialisée dans la réparation, déblocage (Jailbreak) et désimlockage des <b style="color:#F39">iPhones 3, 3GS, 4, 4S et 5</b>. Les 6 ans d’expérience de notre équipe nous permet de vous garantir un travail de qualité, rapide et surtout pas cher. GSM EXPRESS vous propose également une large gamme d’accessoires pour votre iPhone : pochettes, oreillettes, chargeurs, batteries...
                    <a class="reparation" href="reparation-iphone.php">Réparation</a>
                    <a class="accessoire" href="accessoires-iphone.php">Accessoires</a>
                    <a class="deblocage" href="deblocage-iphone.php">Déblocage</a>
                    </p>
                    
                </div>
                <div class="bas_iphone"></div>
            </div>
            <div class="product_mobile">
            	<div class="mobile">
                	<div class="head_product">
                    	<h2>Autres Marques Gsm </h2>
                    </div>
                    <img src="images/gsm.jpg" />
                    <p><strong>GSM EXPRESS</strong> répare, débloque, désimlocke les smart-phones de la plupart des fabricants GSM (Samsung, Nokia, Motorola, HTC, LG, BLACKBERRY). Quel soit neuf ou moins récent, nous avons la solution pour votre mobile. De plus nous disposons d’une large gamme d’accessoires pas chers pour votre modèle.</p>
                    <a href="reparation-mobiles.php?id=5" class="active">Nokia</a>
                    <a href="reparation-mobiles.php?id=6" class="noactive">Motorola</a>
                    <a href="reparation-mobiles.php?id=3" class="noactive">HTC</a>
                    <a href="reparation-mobiles.php?id=1" class="noactive">Samsung</a>
                </div>
                <div class="bas_mobile"></div>
            </div>
            <div class="product_informatique">
            	<div class="informatique">
                	<div class="head_product">
                    	<h2>Informatique</h2>
                    </div>
                    <img src="images/informatique.jpg" />
                    <p><strong>GSM EXPRESS</strong> intervient en magasin et chez vous pour tous vos soucis informatiques. Votre PC ou PC portable est infecté par des virus et vous voulez sauvegarder vos données et réinstaller le système, votre PC est endommagé et ne redémarre pas, votre PC a besoin de puissance ou d’espace de stockage, il ne se recharge plus... Venez nous voir ou appelez nous et l’un de nos techniciens se  chargera de réparer votre matériel.</p>
                    <a class="reparation" href="reparation-informatique.php">Réparation</a>
                    <a class="accessoire" href="accessoires-informatique.php">Accessoires</a>
                    <a class="deblocage" href="deblocage-informatique.php">Déblocage</a>
                </div>
                <div class="bas_informatique"></div>
            </div>
            <div class="product_ipad">
            	<div class="ipad">
                	<div class="head_product">
                    	<h2>Ipad et Mini Ipad</h2>
                    </div>
                    <img src="images/ipad.jpg" />
                    <p><strong>GSM EXPRESS</strong> offre un service de réparation garanti et rapide pour votre IPAD. La vitre de votre iPad est cassée, le tactile ne marche plus, les boutons Menu ou Allumage dysfonctionnent… Pas de souci ! L’équipe GSM EXPRESS répare votre panne vite et bien!<br /> Nos accessoires iPad vous permettrons également de personnaliser votre iPad et le rendre à votre image.<br /><br /></p>
                    <a class="reparation" href="reparation-ipad-mini-ipad.php">Réparation</a>
                    <a class="accessoire" href="accessoires-ipad-mini-ipad.php">Accessoires</a>
                    <a class="deblocage" href="deblocage-ipad-mini-ipad.php">Déblocage</a>
                </div>
                <div class="bas_informatique"></div>
            </div>
            <div class="product_jeux">
            	<div class="jeux">
                	<div class="head_product">
                    	<h2>Consoles de jeux</h2>
                    </div>
                    <img src="images/console_jeux.jpg" />
                    <p>Vous avez une console de jeu PS3, PS2, XBOX, WII ou DS mais elle ne marche plus! Venez nous voir et nos techniciens se charge de réparer votre console. Un diagnostic gratuit est fait sur place pour déterminer la nature du problème. La réparation est aussi garantie et vous repartez avec votre console en parfait état de marche.<br />Le meilleur choix d’accessoires de vos consoles PS3, PS2, XBOX, WII vous est proposé </p>
                    <a class="reparation" href="reparation-consoles-jeux.php">Réparation</a>
                    <a class="accessoire" href="accessoires-consoles-jeux.php">Accessoires</a>
                    <a class="deblocage" href="deblocage-consoles-jeux.php">Déblocage</a>
                </div>
                <div class="bas_informatique"></div>
            </div>
            
        </div>
    </div>


    <script type="text/javascript">
    swfobject.registerObject("FlashID");
    </script>