<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Newsletter</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" class="default-tab">Liste</a></li> <!-- href must be unique and match the id of target div -->
						
					</ul>
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
						<table>
							
							<thead>
								<tr>
								   <th>Email</th>
								   <th>Date Inscription</th>
								   <th></th>
								   <th></th>
								   <th>Actions</th>
								</tr>
								
							</thead>
						 
							
						 
							<tbody>
								
								<?php 
								foreach($this->emails as $ligne){
									
									
								?>
								
								<tr>
									<td><?php echo $this->escape($ligne->email); ?></td>
									<td><?php echo $this->escape($ligne->date); ?></td>
									<td></td>
									<td></td>
									<td>
										<!-- Icons -->
										
										 <a href="/administration/newsletter/supprimer/id/<?php echo $ligne->id ?>" title="Delete"><img src="<?php echo $this->baseUrl(); ?>/adminres/images/icons/cross.png" alt="Delete" /></a> 
									</td>
								</tr>
								<?php } ?>
								
							</tbody>
							
						</table>
						
					</div> <!-- End #tab1 -->
					
					 <!-- End #tab2 -->        
					
				</div> <!-- End .content-box-content -->
				
			</div>