<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Destinations</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" class="default-tab">Liste</a></li> <!-- href must be unique and match the id of target div -->
						<li><a href="#tab2">Ajouter</a></li>
					</ul>
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
						<table>
							
							<thead>
								<tr>
								   <th>Titre</th>
								   <th></th>
								   <th></th>
								   <th></th>
								   <th>Actions</th>
								</tr>
								
							</thead>
						 
							
						 
							<tbody>
								
								<?php 
								foreach($this->destinations as $ligne){
									
									
								?>
								
								<tr>
									<td><?php echo $this->escape($ligne->libelle); ?></td>
									<td></td>
									<td></td>
									<td></td>
									<td>
										<!-- Icons -->
										 <a href="/administration/destination/modifier/id/<?php echo $ligne->id ?>" title="Edit"><img src="<?php echo $this->baseUrl(); ?>/adminres/images/icons/pencil.png" alt="Edit" /></a>
										 <a href="/administration/destination/supprimer/id/<?php echo $ligne->id ?>" title="Delete"><img src="<?php echo $this->baseUrl(); ?>/adminres/images/icons/cross.png" alt="Delete" /></a> 
									</td>
								</tr>
								<?php } ?>
								
							</tbody>
							
						</table>
						
					</div> <!-- End #tab1 -->
					
					<div class="tab-content" id="tab2">
					
						<form action="" method="post" enctype="multipart/form-data">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								
								<p>
									<label>Titre</label>
									<input class="text-input medium-input" type="text" id="libelle" name="libelle" />
								</p>
                                
                               
								<p>
									<label>Description</label>
									<textarea class="text-input textarea wysiwyg" id="description" name="description" cols="79" rows="15"></textarea>
								</p>
								
								
								
								
								
							
								<p>
									<input class="button" type="submit" value="Ajouter" />
								</p>
								
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						
					</div> <!-- End #tab2 -->        
					
				</div> <!-- End .content-box-content -->
				
			</div>