<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Produits</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" <?php echo ($this->ong==0)?'class="default-tab"':'' ?>>Liste</a></li> <!-- href must be unique and match the id of target div -->
						<li><a href="#tab2" <?php echo ($this->ong==1)?'class="default-tab"':'' ?>>Ajouter</a></li>
					</ul>
					<div class="clear"></div>
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content <?php echo ($this->ong==0)?'default-tab':'' ?>" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
						<table>
							
							<thead>
								<tr>
								   <th>Titre</th>
								   <th>Categorie</th>
								   <th>Tarif</th>
								   <th></th>
								   <th>Actions</th>
								</tr>
								
							</thead>
						 
							<?php /* <tfoot>
								<tr>
									<td colspan="5">
										
										
										<div class="pagination">
											<a href="#" title="First Page">&laquo; First</a><a href="#" title="Previous Page">&laquo; Previous</a>
											<a href="#" class="number" title="1">1</a>
											<a href="#" class="number" title="2">2</a>
											<a href="#" class="number current" title="3">3</a>
											<a href="#" class="number" title="4">4</a>
											<a href="#" title="Next Page">Next &raquo;</a><a href="#" title="Last Page">Last &raquo;</a>
										</div> <!-- End .pagination -->
										<div class="clear"></div>
									</td>
								</tr>
							</tfoot> */?>
						 
							<tbody>
								
								<?php 
								foreach($this->produits as $ligne){
									$categorie=FNC::getObjetById($this->categories,$ligne->categorie_id);
									
								?>
								
								<tr>
									<td><?php echo $this->escape($ligne->titre); ?></td>
									<td><?php echo ($categorie)?$categorie->libelle:'------' ?></td>
									<td><b></b></td>
									<td></td>
									<td>
										<!-- Icons -->
										 <a href="/administration/produits/modifier/id/<?php echo $ligne->id ?>" title="Edit"><img src="<?php echo $this->baseUrl(); ?>/adminres/images/icons/pencil.png" alt="Edit" /></a>
										 <a href="/administration/produits/supprimer/id/<?php echo $ligne->id ?>" title="Delete"><img src="<?php echo $this->baseUrl(); ?>/adminres/images/icons/cross.png" alt="Delete" /></a> 
									</td>
								</tr>
								<?php } ?>
								
							</tbody>
							
						</table>
						
					</div> <!-- End #tab1 -->
					
					<div class="tab-content <?php echo ($this->ong==1)?'default-tab':'' ?>" id="tab2">
					
						<form action="" method="post" enctype="multipart/form-data">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								
								<p>
									<label>Titre</label>
									<input class="text-input medium-input" type="text" id="titre" name="titre" />
								</p>
                                
                                 <p>
									<label>Mini description</label>
									<textarea class="text-input textarea wysiwyg" id="minidescription" name="minidescription" cols="79" rows="5"></textarea>
								</p>
								<p>
									<label>Description</label>
									<textarea class="text-input textarea wysiwyg" id="description" name="description" cols="79" rows="15"></textarea>
								</p>
								
								
								
								
								<p>
									<label>Categorie</label>              
									<select name="categorie_id" class="small-input">
										<option value="0"></option>
                                        <?php 
										foreach($this->categories as $catligne){
										?>
										<option value="<?php echo $catligne->id; ?>"><?php echo $this->escape($catligne->libelle); ?></option>
                                        <?php 
										}
										?>
									</select> 
								</p>
								<p>
									<label>Image (200px / 160px)</label>
									<input type="file" id="image" name="image" />
									<label for=""><input type="checkbox" name="recadrer" value="1"> Recadrer l'image</label>
								</p>
								
								<p>
									<input class="button" type="submit" value="Ajouter" />
								</p>
								
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						
					</div> <!-- End #tab2 -->        
					
				</div> <!-- End .content-box-content -->
				
			</div>