<script>

$(document).ready(function(){
	$( "#prochain_depart" ).datepicker();
});
</script>

<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Modifier</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" <?php echo (!$this->ong)?'class="default-tab"':'' ?>>Modifier</a></li> <!-- href must be unique and match the id of target div -->
                        
                        
					</ul>
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content <?php echo (!$this->ong)?'default-tab':'' ?>" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
					
						<form action="" method="post" enctype="multipart/form-data">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								
								<p>
									<label>Nom</label>
									<input class="text-input medium-input" type="text" id="libelle" name="libelle" value="<?php echo $this->escape($this->produit->libelle); ?>" />
								</p>
                                
							

								
								
								
								<p>
									<label>Categorie</label>              
									<select name="categorie_id" class="small-input">
										<option value="0"></option>
                                        <?php 
										foreach($this->categories as $catligne){
										?>
										<option value="<?php echo $catligne->id; ?>" <?php echo ($this->produit->categorie_id==$catligne->id)?'selected="selected"':'' ?>><?php echo $this->escape($catligne->libelle); ?></option>
                                        <?php 
										}
										?>
									</select> 
								</p>
                                

                                
                                




								
                                <p>
                                	<?php if($this->produit->image!=''){ ?>
                           	  		<div><img src="/photos/<?php echo $this->produit->image ?>" width="233" /></div>
                                    <?php } ?>
									<label>Image (250px / 200px)</label>
									<input type="file" id="image" name="image" />
									<label for=""><input type="checkbox" name="recadrer" value="1"> Recadrer l'image</label>
								</p>

								<p>
									<input class="button" type="submit" value="Modifier" />
								</p>
								
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						
						
					</div> <!-- End #tab1 -->
                    
				</div> <!-- End .content-box-content -->
				
			</div>