<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Modifier</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" class="default-tab">Modifier</a></li> <!-- href must be unique and match the id of target div -->
                        
					</ul>
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
					
						<form action="" method="post" enctype="multipart/form-data">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								
								<p>
									<label>Titre</label>
									<input class="text-input medium-input" type="text" id="libelle" name="libelle" value="<?php echo $this->escape($this->prix->libelle); ?>" />
								</p>
                                <p>
									<label>Signe </label>
									<select class="text-input small-input" id="signe" name="signe">
										<option value="1" <?php echo ($this->prix->signe==1)?'selected="selected"':'' ?>>Inférieur ou égal</option>
                                        <option value="2" <?php echo ($this->prix->signe==2)?'selected="selected"':'' ?>>Entre</option>
                                        <option value="3" <?php echo ($this->prix->signe==3)?'selected="selected"':'' ?>>Superieur ou égal</option>
                                    </select>
								</p>
                              	 <p>
									<label>Prix 1 </label>
									<input class="text-input small-input" type="text" id="val1" name="val1" value="<?php echo $this->escape($this->prix->val1); ?>" />
								</p>
								
								<p>
									<label>Prix 2 </label>
									<input class="text-input small-input" type="text" id="val2" name="val2" value="<?php echo $this->escape($this->prix->val2); ?>" />
								</p>
								<p>
									<label>Ordre</label>
									<input class="text-input small-input" type="text" id="ordre" name="ordre" value="<?php echo $this->escape($this->prix->ordre); ?>" />
								</p>
								
								
								
								
							
								<p>
									<input class="button" type="submit" value="Ajouter" />
								</p>
								
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						
						
					</div> <!-- End #tab1 -->
                    
                    
					
				</div> <!-- End .content-box-content -->
				
			</div>