
    <div id="container">
    	<div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Contact</a></div>
          <div class="main_contact">
        	<form name="" method="post" action="" class="ctt_form">
			<?php 
if(isset($_POST['send_ctt'])){
		
		$headers ='From: '. $_POST['nom'] ."<$_POST[email]>\n";
		$headers .='Reply-To:'. $_POST['email'] ."\n"; 
		$headers .='Content-Type: text/html; charset="utf-8"'."\n";
		$headers .='Content-Transfer-Encoding: 8bit';
		$msg ='<html>
			<body>
			<strong>Nom</strong> : '.$_POST['nom'].'<br />
			<strong>Prenom</strong> : '.$_POST['prenom'].'<br />
			<strong>E-mail</strong> : '.$_POST['email'].'<br />
			<strong>Adresse</strong> : '.$_POST['adresse'].'<br /><br />
			<strong>Telephone</strong> : '.$_POST['tel'].'<br /><br />
			
			<strong>Message</strong> : '.nl2br($_POST['msg']).'<br />
			</body>
			</html>';
		@mail("contact@gsm-express.fr", "CONTACT GSM EXPRESS", $msg, $headers);
		@mail("developpement@taktilcommunication.com", "CONTACT GSM EXPRESS", $msg, $headers);
		
        ?>
            <div style="color:#eb118b; padding:10px; height:50px; padding-top:120px;  width:460px; text-align:center">Nous avons bien re&ccedil;u votre message</div>
            <?php
        }else{

?>
<table width="420" border="0" cellspacing="4" cellpadding="1">

  
  <tr>
    <td height="50">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td width="40">&nbsp;</td>
    <td width="70"><strong>Nom </strong></td>
    <td width="5">:</td>
    <td><input type="text" name="nom" class="inp_ctt_b1" /></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Prénom </strong></td>
    <td>:</td>
    <td><input name="prenom" type="text" class="inp_ctt_b1" id="prenom" /></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Email </strong></td>
    <td>:</td>
    <td><input name="email" type="text" class="inp_ctt_b1" id="email" /></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Adresse </strong></td>
    <td>:</td>
    <td><input name="adresse" type="text" class="inp_ctt_b1" id="adresse" /></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td><strong>Téléphone </strong></td>
    <td>:</td>
    <td><input name="tel" type="text" class="inp_ctt_b1" id="tel" /></td>
    </tr>
  
  <tr>
    <td valign="top">&nbsp;</td>
    <td valign="top"><strong>Message </strong></td>
    <td valign="top">:</td>
    <td><textarea name="msg" class="inp_ctt_b1" id="msg" style="width:270px; height:100px"></textarea></td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>
      <input type="submit" class="ctt_envoyer" value="" name="send_ctt" />
    </td>
    </tr>
  <tr>
    <td colspan="4"></td>
  </tr>
  </table>
  <?php } ?>
          </form>

        	<div class="ctt_adress">
            <u>Contactez-nous aussi :</u>
<span><br />
Par courrier :</span> 30, Rue des SARRAZINS, 59000 - LILLE.<br />
<span>Par téléphone :</span> 03 20 15 93 40</div>
      <div class="img_iphone_ctt"><img src="images/iphone_contact.gif" width="272" height="312" /></div></div>		
    	  
            
        </div>
    </div>