<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Pages</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" class="default-tab">Liste pages</a></li> 
					</ul>
					<div class="clear"></div>
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
						<table>
							
							<thead>
								<tr>
								   <th>Titre</th>
								   <th></th>
								   <th></th>
								   <th></th>
								   <th>Actions</th>
								</tr>
								
							</thead>
						 
							
						 
							<tbody>
								
								<?php 
								foreach($this->pages as $ligne){
									
								?>
								
								<tr>
									<td><?php echo $this->escape($ligne->titre); ?></td>
									<td></td>
									<td></td>
									<td></td>
									<td>
										<!-- Icons -->
										 <a href="/administration/pages/modifier/id/<?php echo $ligne->id ?>" title="Edit"><img src="<?php echo $this->baseUrl(); ?>/adminres/images/icons/pencil.png" alt="Edit" /></a>
										 
									</td>
								</tr>
								<?php } ?>
								
							</tbody>
							
						</table>
						
					</div> <!-- End #tab1 -->
					
				</div> <!-- End .content-box-content -->
				
			</div>