<div class="content-box"><!-- Start Content Box -->
				
				<div class="content-box-header">
					
					<h3>Modifier Page</h3>
					
					<ul class="content-box-tabs">
						<li><a href="#tab1" <?php echo (!$this->ong)?'class="default-tab"':'' ?>>Modifier</a></li> <!-- href must be unique and match the id of target div -->
						
                        <li><a href="#tab4" <?php echo ($this->ong=='photos')?'class="default-tab"':'' ?>>Photos</a></li>
                        
					</ul>
					
					<div class="clear"></div>
					
				</div> <!-- End .content-box-header -->
				
				<div class="content-box-content">
			   
					<div class="tab-content <?php echo (!$this->ong)?'default-tab':'' ?>" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
					
					
						<form action="" method="post" enctype="multipart/form-data">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								
								<p>
									<label>Titre</label>
									<input class="text-input medium-input" type="text" id="titre" name="titre" value="<?php echo $this->escape($this->article->titre); ?>" />
								</p>
                                
                                <p>
									<label>Titre 2 </label>
									<input class="text-input medium-input" type="text" id="soustitre" name="soustitre" value="<?php echo $this->escape($this->article->soustitre); ?>" />
								</p>
                                
                                <?php /*  <p>
									<label>Mini description</label>
									<textarea class="text-input textarea" id="minidescription" name="minidescription" cols="79" rows="5"><?php echo $this->escape($this->article->minidescription); ?></textarea>
								</p> */?>
								<p>
									<label>Description</label>
									<textarea class="text-input textarea ckeditor" id="description" name="description" cols="79" rows="15"><?php echo $this->escape($this->article->description); ?></textarea>
								</p>
                                
                                
								
								<p>
									<input class="button" type="submit" value="Modifier" />
								</p>
								
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						
						
					</div> <!-- End #tab1 -->
					
                    <div class="tab-content <?php echo ($this->ong=='photos')?'default-tab':'' ?>" id="tab4"> <!-- This is the target div. id must match the href of this div's tab -->
						<form action="" method="post" enctype="multipart/form-data" class="formajout">
							
							<fieldset> <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
								<p>
									<label>Ajouter une photo</label>
									<input type="file" id="image" name="image" />
								</p>
								
								<p>
									<input class="button" type="submit" name="subaddphoto" value="Ajouter" />
								</p>
								
							</fieldset>
							
							<div class="clear"></div><!-- End .clear -->
							
						</form>
						<div class="listphoto">
                        	<?php foreach($this->photos as $ligne){ ?>
                        	<div class="photoligne">
                            	<img src="/photos/<?php echo $ligne->src ?>" width="200" />
                                <a href="/administration/incentive/delphoto/id/<?php echo $ligne->id ?>">supprimer</a>
                                
                            </div>
                            <?php } ?>
                        </div>
						
					</div> <!-- End #tab1 -->
				    
					
				</div> <!-- End .content-box-content -->
				
			</div>