
    <div id="container">
      <div class="content">
        <div class="navigation">Vous êtes ici : <a href="">Réparation emploi</a><br /><br /></div>
          <div class="main_mode_emploi">
            
          <table width="900" border="0" align="center" cellpadding="0" cellspacing="0" style="text-align:left; float:left; margin:auto;">
  <tr>
    <td>&nbsp;</td>
    <td height="40">&nbsp;</td>
    <td width="23">&nbsp;</td>
    <td>&nbsp;</td>
    <td width="73">&nbsp;</td>
    <td width="200">&nbsp;</td>
  </tr>
  <tr>
    <td width="14">&nbsp;</td>
    <td width="316"><table width="200" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="ttr_emploi">Réparer votre<br />
          téléphone</div></td>
        <td width="10">&nbsp;</td>
        <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/emploi_iphone.gif" width="66" height="66" /></td>
      </tr>
    </table></td>
    <td>&nbsp;</td>
    <td width="274"><table width="200" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="ttr_emploi">Réparer votre<br />
          PC</div></td>
        <td width="10">&nbsp;</td>
        <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/emploi_pc_portable.gif" width="66" height="66" /></td>
      </tr>
    </table></td>
    <td>&nbsp;</td>
    <td><table width="200" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="ttr_emploi">Pannes les plus fréquentes</div></td>
        <td width="10">&nbsp;</td>
        <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/emploi_iphone_2.gif" width="78" height="66" /></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td valign="top">&nbsp;</td>
    <td valign="top"><div class="desc_emploi"><span class="rose_color">GSM EXPRESS</span> est spécialisé dans la réparation de smart-phones toutes marques. Grâce à notre expérience de plusieurs années au service des professionnels et particuliers, nous vous garantissons un travail sérieux et rapide.<br />
<br /><br />
En attendant la réparation de votre téléphone, <span class="rose_color">GSM EXPRESS</span> met à votre disposition un mobile de prêt.</div></td>
    <td align="center"><img src="<?php echo $this->baseUrl(); ?>/images/sep_recycler.gif" width="10" height="200" /></td>
    <td valign="top"><div class="desc_emploi">Nos vous proposons également un service de réparation de PC. Votre écran est cassé, votre PC  ne se recharge plus, vous voulez le formater ou réinstaller le système.<br />
<br />


C'est simple, appelez nous ou venez en boutique. Nos techniciens feront un diagnostic immédiat de votre matériel.

</div></td>
    <td align="center"><img src="<?php echo $this->baseUrl(); ?>/images/sep_recycler.gif" width="10" height="200" /></td>
    <td valign="top"><div class="desc_emploi">
      <p>Les pannes les plus fréquentes :<br />
        Écran cassé, tactile cassé, défaut de rechargement, problème d'allumage, coque abimée, défaut micro, haut-parleur...</p>
      <p>Quelque soit votre panne, nos techniciens sont à votre disposition pour tout renseignement et diagnostic.</p>
    </div></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td align="right"><a href="reparation-iphone.php"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/devis-en-ligne-btn.gif" width="133" height="36" border="0" /></a></td>
    <td>&nbsp;</td>
    <td align="right"><a href="reparation-informatique.php"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/devis-en-ligne-btn.gif" width="133" height="36" border="0" /></a></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
        </table>
          <div class="list_logos">
          <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/sony_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/toshiba_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/samsung_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/apple_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/lenovo_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/pachard_bell_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/nokia_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/sony_erricson_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/blackberry_logo.gif" width="76" height="27" border="0" /></span>
            
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/compaq_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/acer_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/dell_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/ibm_logo.gif" width="76" height="27" border="0" /></span>
            
            
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/asus_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/fujistu_simens_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/lg_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/htc_logo.gif" width="76" height="27" border="0" /></span>
            <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/alcatel_logo.gif" width="76" height="27" border="0" /></span>
            
        <span><img src="<?php echo $this->baseUrl(); ?>/images/emploi/motorola_logo.gif" width="76" height="27" border="0" /></span></div>
            
        <div class="ttr_ong_emploi">GSM EXPRESS vous propose trois mode de réparation de votre matériel :</div> 
        <table width="900" border="0" align="center" cellpadding="0" cellspacing="0" style="text-align:left">
  <tr>
    <td width="240" height="40">&nbsp;</td>
    <td width="40">&nbsp;</td>
    <td width="300">&nbsp;</td>
    <td width="30">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td valign="top"><table width="240" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><table width="240" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><strong>REPARATION<br />
              EXPRESS</strong><br />
              ( Sur Place )</td>
            <td>&nbsp;</td>
            <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/rep_mode_1.gif" width="70" height="58" /></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td height="20">&nbsp;</td>
      </tr>
      <tr>
        <td class="desc_emploi"><p><strong>Devis et réparation sur place.</strong></p>
          <p>En venant directement dans notre magazin, un technicien vous fera un diagnostic et un devis immédiat.</p>
          <p>En moins de 30 minutes, votre appareil sera réparé et testé.</p>
          <p>Sous condition de disponibité des piéces de rechanges.</p></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table></td>
    <td align="center"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/sep_mode.gif" width="13" height="321" /></td>
    <td valign="top"><table width="300" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><table width="300" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><strong>COLISS EXPRESS</strong><br />
              ( Colissimo 48H )</td>
            <td>&nbsp;</td>
            <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/rep_mode_2.gif" width="109" height="58" /></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td height="20">&nbsp;</td>
      </tr>
      <tr>
        <td class="desc_emploi"><p><b>1. </b>Compléter le formulaire ci-après (<a href="pdf/demande-de-reparation.pdf" target="_blank" style="color:#09F">demande de réparation</a>)<br />
          - Emballez soigneusement votre appareil.<br />
          - Etablir un chéque à l'ordre de la société PHONEA SARL
          <br />
          - Envoyez le tout à l'adresse suivante :<br />
          <br />
          <b>GSM EXPRESS<br />
30 RUE DES SARRAZINS<br />
59000 LILE</b><br />
<br />
<b>2.</b> Dès réception de votre matériel, un technicien le répare et le teste.<br />
<br />
<b>3.</b> Votre matériel vous est retourné le jour même.</p></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table></td>
    <td align="center"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/sep_mode.gif" width="13" height="321" /></td>
    <td valign="top"><table width="280" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><table width="280" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><strong>REPARATION AU BUREAU</strong><br />
              ( Chez Vous )</td>
            <td>&nbsp;</td>
            <td align="right"><img src="<?php echo $this->baseUrl(); ?>/images/emploi/rep_mode_3.gif" width="109" height="58" /></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td height="20">&nbsp;</td>
      </tr>
      <tr>
        <td class="desc_emploi"><p>Vous travaillez et vous n'avez pas le temps de passer à notre magazin, vous êtes chez vous. Sur simple appel, nous vous envoyons un coursier qui recupère votre matériel et vous le ramène après avoir été réparé et testé par nos techniciens.</p>
          <p>Notre équipe s'engage à vous restituer votre matériel en <b>2h</b>.</p>
          <p>En attendant votre appareil, <b class="rose_color">GSM EXPRESS</b> met à votre disposition un gsm de remplacement.</p></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><img src="<?php echo $this->baseUrl(); ?>/images/emploi/appeler_nous.gif" width="289" height="43" /></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><div style="font-size:10px; color:#CCC"><br />
      Ce service est disponible sur la région de Lille et ses environs. Sous conditions de disponibilités des pièces de rechanges.</div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
   
        </div>    
        
            
        </div>
    </div>
</body>
</html>
