<div id="container">
      <div class="content">
          <div class="navigation">Vous êtes ici : Iphone > <a href="">Réparation</a></div>
          <div class="left_page">
            <div class="product">
                  <div class="bande_product">
                      <div class="active"><h2>Réparation</h2></div>
                      <div class="noactive"><h2><a href="accessoires-iphone.php">Accessoires</a></h2></div>
                      <div class="noactive"><h2><a href="deblocage-iphone.php">Déblocage</a></h2></div>
                    </div>
                    <p>GSM EXPRESS est spécialisé dans la réparation de smart-phones toutes marques. Grâce à notre expérience de plusieurs années au service des professionnels et particuliers, nous vous garantissons un travail sérieux et rapide. En attendant la réparation de votre téléphone, GSM EXPRESS met à votre disposition un mobile de prêt.<br /><br />

Préparez votre devis en ligne en cochant votre modèle de mobile et votre panne ainsi que vore mode de réparation. Suivez les étapes suivantes :</p>
        <div class="bande_modele">
                  <h2>Choisir votre modèle d’iphone à réparer</h2>
                </div>
                <div class="cadre_product">
                  <div class="produit">
                      <img src="<?php echo $this->baseUrl(); ?>/images/ipohne_3gs.jpg" onclick="selection_iphone(0,2)"  />
                        <a href="javascript:selection_iphone(0,2)" class="noactive">Iphone 3GS</a>
                    </div>
                  <div class="produit">
                      <img src="<?php echo $this->baseUrl(); ?>/images/iphone_3g.jpg" onclick="selection_iphone(1,1)"  />
                        <a href="javascript:selection_iphone(1,1)" class="noactive">Iphone 3G</a>
                    </div>
                  <div class="produit">
                      <img src="<?php echo $this->baseUrl(); ?>/images/iphone_4g.jpg" onclick="selection_iphone(2,3)"   />
                        <a href="javascript:selection_iphone(2,3)" class="noactive">Iphone 4G</a>
                    </div>
                  <p>Pour les autres marques, appellez nous. Nos conseillés sont à votre écoute.</p>
                </div>
                <div class="bande_modele">
                  <h2>Choisir votre panne</h2>
                </div>
                <div id="pannes"> </div>
                <div class="bande_modele">
                  <h2>Choisir votre mode de réparation</h2>
                </div>
                <div id="mode">
                  <div class="mode_paiement">
                      <img src="<?php echo $this->baseUrl(); ?>/images/sur_place.jpg" onclick="selection_modeiphone(0,1)" />
                        <a href="javascript:selection_modeiphone(0,1);" class="active">Réparation express<br /><span>( Sur place )</span></span></a>
                        <a href="reaparation-emploi.html" class="savoir">+  En savoir plus</a>
                    </div>
                  <div class="mode_paiement">
                      <img src="<?php echo $this->baseUrl(); ?>/images/colis.jpg" class="noactive_imgpane" onclick="selection_modeiphone(1,2)" />
                        <a href="javascript:selection_modeiphone(1,2);" class="noactive">Réparation express<br /><span>( Sur place )</span></span></a>
                        <a href="reaparation-emploi.html" class="savoir">+  En savoir plus</a>
                    </div>
                </div>
              </div>
            </div>
            <div class="right_page">
              <div class="devis">
              <div class="head_devis">
                  <h2>Devis immédiat</h2>
                </div>
                <div id="detail_devis"></div>
                <form method="post" action="pdf/getdevis.php" enctype="multipart/form-data" onsubmit="return validate_devis();">
                <div class="devis_form_input">
                  <label for="" class="devis_label">Nom &amp; Pr&eacute;nom : </label>
                    <input type="text" class="devis_input" name="nom" id="nom" />
                </div>
              <div class="devis_form_input">
                  <label for="" class="devis_label">Adresse : </label>
                    <textarea class="devis_textarea" rows="" cols="" name="adresse" id="adresse"></textarea>
                </div>
              <div class="devis_form_input">
                <label for="" class="devis_label">Email  : </label>
                  <input type="text" class="devis_input" name="email" id="email" />
                </div>
              <div class="devis_form_input">
                <label for="" class="devis_label">Téléphone  : </label>
                  <input type="text" class="devis_input" name="tel" id="tel" />
                </div>
              <div class="devis_form_input">
                <label for="" class="devis_label">Code IEMI, Adresse MAC ou Référence<br />
                de votre matériel  : </label>
                  <input type="text" class="devis_input" name="code" id="code" />
              </div>
              <div class="devis_form_input">
                <label for="" class="devis_label">Mode de paiement : </label>
                  <span class="devis_radio" id="mode1"></span>                    
                    <span class="devis_radio_label">Par Chéque </span>
                  <span class="devis_radio" id="mode2"></span>
                    <span class="devis_radio_label">En boutique</span>
                    <input type="hidden" name="mode_p" id="mode_p" />
              </div>
              <div class="devis_form_input">
                <input type="submit" class="devis_submit" name="send_reps_iphone" value="" />
              </div>
              </form>
            </div>
            </div>
            
           
        </div>
    </div>